// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat_messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatMessagesForConversation = `-- name: GetChatMessagesForConversation :many
SELECT id, content, conversation_id, sender_id, created_at, updated_at
FROM chat_messages
WHERE conversation_id = $1
`

type GetChatMessagesForConversationRow struct {
	ID             int64
	Content        string
	ConversationID int64
	SenderID       int64
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

func (q *Queries) GetChatMessagesForConversation(ctx context.Context, conversationID int64) ([]GetChatMessagesForConversationRow, error) {
	rows, err := q.db.Query(ctx, getChatMessagesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatMessagesForConversationRow
	for rows.Next() {
		var i GetChatMessagesForConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ConversationID,
			&i.SenderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
