// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversation_participants.sql

package database

import (
	"context"
)

const createConversationParticipant = `-- name: CreateConversationParticipant :one
INSERT INTO conversation_participants(conversation_id, user_id)
VALUES(
    $1,
    $2
)
RETURNING id, conversation_id, user_id
`

type CreateConversationParticipantParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) CreateConversationParticipant(ctx context.Context, arg CreateConversationParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, createConversationParticipant, arg.ConversationID, arg.UserID)
	var i ConversationParticipant
	err := row.Scan(&i.ID, &i.ConversationID, &i.UserID)
	return i, err
}
