// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: conversations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversationForParticipants = `-- name: GetConversationForParticipants :one
SELECT conversation_id
FROM conversation_participants 
WHERE user_id IN ($1,$2)
GROUP BY conversation_id
HAVING COUNT(DISTINCT user_id) = 2
`

type GetConversationForParticipantsParams struct {
	UserID   int64
	UserID_2 int64
}

func (q *Queries) GetConversationForParticipants(ctx context.Context, arg GetConversationForParticipantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConversationForParticipants, arg.UserID, arg.UserID_2)
	var conversation_id int64
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getConversationsForUser = `-- name: GetConversationsForUser :many
WITH UserConversations AS (
    SELECT cp.conversation_id
    FROM conversation_participants cp
    WHERE cp.user_id = $1
),
SingleOtherParticipantConversationIds AS (
    SELECT
        cp_current_user.conversation_id,
        cp_other_user.user_id AS other_user_id
    FROM conversation_participants cp_current_user
    JOIN conversation_participants cp_other_user
        ON cp_current_user.conversation_id = cp_other_user.conversation_id
    WHERE
        cp_current_user.user_id = $1
        AND cp_other_user.user_id != $1 
    GROUP BY cp_current_user.conversation_id, cp_other_user.user_id
    HAVING COUNT(cp_current_user.user_id) = 1 
        AND (SELECT COUNT(DISTINCT user_id) FROM conversation_participants WHERE conversation_id = cp_current_user.conversation_id) = 2
),
OtherParticipantDetails AS (
    SELECT
        sop.conversation_id,
        u.id AS other_user_id,
        u.email AS other_user_email,
        u.user_name AS other_user_user_name,
        u.full_name AS other_user_full_name,
        u.profile_image_url AS other_user_profile_image_url,
        u.dob AS other_user_dob,
        u.created_at AS other_user_created_at,
        u.updated_at AS other_user_updated_at

    FROM SingleOtherParticipantConversationIds sop
    JOIN users u ON sop.other_user_id = u.id
),
RankedMessages AS (
    SELECT
        cm.id,
        cm.conversation_id,
        cm.sender_id,
        cm.content,
        cm.created_at,
        cm.updated_at,
        ROW_NUMBER() OVER (PARTITION BY cm.conversation_id ORDER BY cm.created_at DESC, cm.id DESC) as rn
    FROM chat_messages cm
    INNER JOIN UserConversations uc ON cm.conversation_id = uc.conversation_id
)
SELECT
    c.id AS conversation_id,
    c.conversation_type AS conversation_type,
    COALESCE(c.conversation_name, opd.other_user_full_name) AS display_name,
    c.created_at AS conversation_created_at,
    c.updated_at AS conversation_updated_at,
    rm.id AS last_message_id,
    rm.content AS last_message_content,
    rm.conversation_id AS last_message_conversation_id,
    rm.sender_id AS last_message_sender_id,
    rm.created_at AS last_message_created_at,
    rm.updated_at AS last_message_updated_at,
    opd.other_user_id,
    opd.other_user_email,
    opd.other_user_user_name,
    opd.other_user_full_name,
    opd.other_user_profile_image_url,
    opd.other_user_dob,
    opd.other_user_created_at,
    opd.other_user_updated_at
FROM conversations c
INNER JOIN UserConversations uc ON c.id = uc.conversation_id 
INNER JOIN RankedMessages rm ON c.id = rm.conversation_id
LEFT JOIN OtherParticipantDetails opd ON c.id = opd.conversation_id
WHERE rm.rn = 1
`

type GetConversationsForUserRow struct {
	ConversationID            int64
	ConversationType          string
	DisplayName               string
	ConversationCreatedAt     pgtype.Timestamp
	ConversationUpdatedAt     pgtype.Timestamp
	LastMessageID             int64
	LastMessageContent        string
	LastMessageConversationID int64
	LastMessageSenderID       int64
	LastMessageCreatedAt      pgtype.Timestamp
	LastMessageUpdatedAt      pgtype.Timestamp
	OtherUserID               pgtype.Int8
	OtherUserEmail            pgtype.Text
	OtherUserUserName         pgtype.Text
	OtherUserFullName         pgtype.Text
	OtherUserProfileImageUrl  pgtype.Text
	OtherUserDob              pgtype.Date
	OtherUserCreatedAt        pgtype.Timestamp
	OtherUserUpdatedAt        pgtype.Timestamp
}

func (q *Queries) GetConversationsForUser(ctx context.Context, userID int64) ([]GetConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, getConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationsForUserRow
	for rows.Next() {
		var i GetConversationsForUserRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationType,
			&i.DisplayName,
			&i.ConversationCreatedAt,
			&i.ConversationUpdatedAt,
			&i.LastMessageID,
			&i.LastMessageContent,
			&i.LastMessageConversationID,
			&i.LastMessageSenderID,
			&i.LastMessageCreatedAt,
			&i.LastMessageUpdatedAt,
			&i.OtherUserID,
			&i.OtherUserEmail,
			&i.OtherUserUserName,
			&i.OtherUserFullName,
			&i.OtherUserProfileImageUrl,
			&i.OtherUserDob,
			&i.OtherUserCreatedAt,
			&i.OtherUserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
