// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friend_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friend_requests
SET
    request_status = 'accepted',
    accepted_at = NOW() AT TIME ZONE 'UTC',
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE
    id = $1 AND receiver_id = $2 AND request_status = 'pending'
RETURNING id, sender_id, receiver_id, request_status, requested_at, accepted_at, created_at, updated_at
`

type AcceptFriendRequestParams struct {
	ID         int64
	ReceiverID int64
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequest, arg.ID, arg.ReceiverID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.RequestStatus,
		&i.RequestedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friend_requests(sender_id, receiver_id, request_status, requested_at, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC'
)
RETURNING id, sender_id, receiver_id, request_status, requested_at, accepted_at, created_at, updated_at
`

type CreateFriendRequestParams struct {
	SenderID      int64
	ReceiverID    int64
	RequestStatus string
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.SenderID, arg.ReceiverID, arg.RequestStatus)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.RequestStatus,
		&i.RequestedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendRequestsWithSenderDetails = `-- name: GetFriendRequestsWithSenderDetails :many
SELECT
    fr.id as request_id,
    fr.sender_id, 
    fr.receiver_id, 
    fr.request_status,
    fr.requested_at,
    fr.accepted_at,
    fr.created_at as request_created_at,
    fr.updated_at as request_updated_at,
    u.id AS sender_user_id, 
    u.email AS sender_user_email, 
    u.user_name AS sender_user_name,
    u.full_name AS sender_user_full_name,
    u.profile_image_url AS sender_user_profile_image_url,
    u.dob AS sender_user_dob,
    u.created_at AS sender_user_created_at, 
    u.updated_at AS sender_user_updated_at
FROM friend_requests fr
INNER JOIN users u
ON fr.sender_id = u.id
WHERE fr.receiver_id = $1 AND fr.request_status = 'pending'
`

type GetFriendRequestsWithSenderDetailsRow struct {
	RequestID                 int64
	SenderID                  int64
	ReceiverID                int64
	RequestStatus             string
	RequestedAt               pgtype.Timestamp
	AcceptedAt                pgtype.Timestamp
	RequestCreatedAt          pgtype.Timestamp
	RequestUpdatedAt          pgtype.Timestamp
	SenderUserID              int64
	SenderUserEmail           string
	SenderUserName            string
	SenderUserFullName        string
	SenderUserProfileImageUrl pgtype.Text
	SenderUserDob             pgtype.Date
	SenderUserCreatedAt       pgtype.Timestamp
	SenderUserUpdatedAt       pgtype.Timestamp
}

func (q *Queries) GetFriendRequestsWithSenderDetails(ctx context.Context, receiverID int64) ([]GetFriendRequestsWithSenderDetailsRow, error) {
	rows, err := q.db.Query(ctx, getFriendRequestsWithSenderDetails, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestsWithSenderDetailsRow
	for rows.Next() {
		var i GetFriendRequestsWithSenderDetailsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.SenderID,
			&i.ReceiverID,
			&i.RequestStatus,
			&i.RequestedAt,
			&i.AcceptedAt,
			&i.RequestCreatedAt,
			&i.RequestUpdatedAt,
			&i.SenderUserID,
			&i.SenderUserEmail,
			&i.SenderUserName,
			&i.SenderUserFullName,
			&i.SenderUserProfileImageUrl,
			&i.SenderUserDob,
			&i.SenderUserCreatedAt,
			&i.SenderUserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendStatusBetweenTwoUsers = `-- name: GetFriendStatusBetweenTwoUsers :many
SELECT id, sender_id, receiver_id, request_status, requested_at, accepted_at, created_at, updated_at
FROM friend_requests
WHERE sender_id = $1 AND receiver_id = $2
`

type GetFriendStatusBetweenTwoUsersParams struct {
	SenderID   int64
	ReceiverID int64
}

func (q *Queries) GetFriendStatusBetweenTwoUsers(ctx context.Context, arg GetFriendStatusBetweenTwoUsersParams) ([]FriendRequest, error) {
	rows, err := q.db.Query(ctx, getFriendStatusBetweenTwoUsers, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendRequest
	for rows.Next() {
		var i FriendRequest
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.RequestStatus,
			&i.RequestedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT
    fr.id as request_id,
    fr.sender_id, 
    fr.receiver_id, 
    fr.request_status,
    fr.requested_at,
    fr.accepted_at,
    fr.created_at as request_created_at,
    fr.updated_at as request_updated_at,
    u.id AS friend_user_id, 
    u.email AS friend_user_email, 
    u.user_name AS friend_user_name,
    u.full_name AS friend_user_full_name,
    u.profile_image_url AS friend_user_profile_image_url,
    u.dob AS friend_user_dob,
    u.created_at AS friend_user_created_at, 
    u.updated_at AS friend_user_updated_at
FROM friend_requests fr
JOIN users u
ON (fr.receiver_id = $1 AND u.id = fr.sender_id) OR (fr.sender_id = $1 AND u.id = fr.receiver_id)
WHERE
    fr.request_status = 'accepted'
    AND (fr.sender_id = $1 OR fr.receiver_id = $1)
ORDER BY
    fr.accepted_at DESC
`

type GetFriendsRow struct {
	RequestID                 int64
	SenderID                  int64
	ReceiverID                int64
	RequestStatus             string
	RequestedAt               pgtype.Timestamp
	AcceptedAt                pgtype.Timestamp
	RequestCreatedAt          pgtype.Timestamp
	RequestUpdatedAt          pgtype.Timestamp
	FriendUserID              int64
	FriendUserEmail           string
	FriendUserName            string
	FriendUserFullName        string
	FriendUserProfileImageUrl pgtype.Text
	FriendUserDob             pgtype.Date
	FriendUserCreatedAt       pgtype.Timestamp
	FriendUserUpdatedAt       pgtype.Timestamp
}

func (q *Queries) GetFriends(ctx context.Context, receiverID int64) ([]GetFriendsRow, error) {
	rows, err := q.db.Query(ctx, getFriends, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.SenderID,
			&i.ReceiverID,
			&i.RequestStatus,
			&i.RequestedAt,
			&i.AcceptedAt,
			&i.RequestCreatedAt,
			&i.RequestUpdatedAt,
			&i.FriendUserID,
			&i.FriendUserEmail,
			&i.FriendUserName,
			&i.FriendUserFullName,
			&i.FriendUserProfileImageUrl,
			&i.FriendUserDob,
			&i.FriendUserCreatedAt,
			&i.FriendUserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
