// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: interests.sql

package database

import (
	"context"
)

const getAllInterests = `-- name: GetAllInterests :many
SELECT id, name, created_at, updated_at, deleted_at FROM interests
`

func (q *Queries) GetAllInterests(ctx context.Context) ([]Interest, error) {
	rows, err := q.db.QueryContext(ctx, getAllInterests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interest
	for rows.Next() {
		var i Interest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
