// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Interest struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID              int64
	Email           string
	UserName        string
	FullName        string
	ProfileImageUrl sql.NullString
	Dob             sql.NullTime
	HashedPassword  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type UsersHasInterest struct {
	ID         int64
	UserID     int64
	InterestID int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
