// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(content, created_at, updated_at, user_id)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2
)
RETURNING id, content, created_at, updated_at, deleted_at, user_id
`

type CreatePostParams struct {
	Content string
	UserID  int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.Content, arg.UserID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}

const deleteAllPosts = `-- name: DeleteAllPosts :exec
DELETE FROM posts
`

func (q *Queries) DeleteAllPosts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllPosts)
	return err
}
