// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_media.sql

package database

import (
	"context"
)

const createPostMedia = `-- name: CreatePostMedia :one
INSERT INTO post_media(media_url, order_index, created_at, updated_at, post_id)
VALUES(
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, media_url, order_index, created_at, updated_at, deleted_at, post_id
`

type CreatePostMediaParams struct {
	MediaUrl   string
	OrderIndex int32
	PostID     int64
}

func (q *Queries) CreatePostMedia(ctx context.Context, arg CreatePostMediaParams) (PostMedium, error) {
	row := q.db.QueryRow(ctx, createPostMedia, arg.MediaUrl, arg.OrderIndex, arg.PostID)
	var i PostMedium
	err := row.Scan(
		&i.ID,
		&i.MediaUrl,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PostID,
	)
	return i, err
}
